using Crud_Ajax.BAL;
using Npgsql;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? "Host=localhost;Port=5432;Database=Kailas_Sir;Username=postgres;Password=root";

builder.Services.AddTransient<NpgsqlConnection>(_ => new NpgsqlConnection(connectionString));
builder.Services.AddScoped<InternHelper>();

var app = builder.Build();

await InitializeDatabaseAsync(connectionString);

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
        app.UseHttpsRedirection();
}

app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=MVCIntern}/{action=GetAll}/{id?}");

app.Run();

static async Task InitializeDatabaseAsync(string connectionString)
{
    await using var connection = new NpgsqlConnection(connectionString);
    await connection.OpenAsync();

    const string sql = """
        CREATE TABLE IF NOT EXISTS public.t_topics (
            c_topicid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            c_topicname varchar(100) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS public.t_internsdemo (
            c_internid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            c_internname varchar(100) NOT NULL,
            c_gender varchar(1) NOT NULL,
            c_topicid integer REFERENCES public.t_topics(c_topicid),
            c_date_of_presentation date NOT NULL,
            c_status boolean NOT NULL DEFAULT false,
            c_topic_image varchar(500)
        );

        INSERT INTO public.t_topics (c_topicname)
        SELECT topic_name
        FROM (VALUES ('Web Development'), ('Database Systems'), ('Cloud Computing')) AS defaults(topic_name)
        WHERE NOT EXISTS (SELECT 1 FROM public.t_topics);
        """;

    await using var command = new NpgsqlCommand(sql, connection);
    await command.ExecuteNonQueryAsync();
}
